= Completable 

*Available from Jan 2021*

== Title
Paneer Tikka Masala ... with Java CompletableFuture

== Abstract
A take on the recipe using Java Future and CompletableFuture API, through a code kata.

== Description
Create a cooking recipe with a kata for using Future and CompletableFuture. The talk is mostly a coding demo. A recipe for a delicious Indian curry is used to show how Future and CompletableFuture API can help emulate real life.

=== How does one go about with this kata?
==== Steps:
. Follow the steps in the README.
. Fix the recipe code in each part.
. Use HINTs and TODOs.

==== Overview
The code includes two parts:

* Solved recipe for reference.
* Unsolved/failing recipe for you to fix.

====  Note
Attendees will need the following setup:

√ Apache Maven 3.6.x or above. Tested with Apache Maven 3.6.3. +
Link: https://maven.apache.org/download.cgi

√ JDK 11. Tested with OpenJDK 15 +
Link: http://jdk.java.net/15/

√ Your favorite Java IDE. IntelliJ IDEA Ultimate was used to develop this kata.


== Target Audience Experience Level
* [x] Beginner to Intermediate
* [x] Intermediate to Advanced
* [x] Advanced

== Presentation formats

Preferred: Code Kata walkthrough - 60 mins

=== Available as:
* [x] Smaller Presentation - 60 mins
* [x] Medium Presentation - 90 mins
* [x] Code Kata walkthrough - 60 mins
* [x] Smaller Workshop/Lab exercise - 60 mins

= Speaker Bio

include::../AboutChandraGuntur.adoc[]
