= Algebraic in Java: Pattern Matching

*Available from Jun 2021*

== Title
Algebraic in Java: Pattern Matching

== Abstract
Java started with basic pattern matching techniques, recent versions include more intricate ones! Pattern matching is not just limited to `instanceof` checks, there is a lot more, making Java Algebra-friendly & Functional!

This talk is about the future of Java's Pattern Matching with code examples.

== Description
Pattern Matching - the ability to detect a pattern and use it to compute, calculate or extract other values. 

Previous versions of Java included a basic set of pattern matches, mostly relying on the developer to code the matches, the extraction or any other usage. Newer and upcoming versions of Java seem to bring in a lot more enhancements in this area and focus heavily on making Java more of a Functional-style language. 

This talk is on Pattern Matching present and future, and may include speculative changes which may not compile yet (or ever). The intent is to share some ideas on Pattern Matching, some code samples and discuss the benefits and importance of these new language additions to the language.

== Target Audience Experience Level
* [x] Beginner to Intermediate
* [x] Intermediate to Advanced
* [x] Advanced

== Submission Notes
This session is intended to be completely driven from my IDE. The content will be very similar to an earlier presented talk on "Algebraic In Java - An Introduction", presented at Devnexus 2021 (link below). The talk at Devnexus was well-attended and was quite well-mentioned in social media as well.

If the talk is intended to be pre-recorded, the link to the code will be embedded in the video. If the format is to present live, the QR code will be embedded in the IDE for folk to checkout the GitHub project.

There are no presentation slides for this session. 

*Time constraint*: I will need two weeks before the event, to get the approvals at work to present (not an issue, it is just the standard time needed to get approvals).

Link to related previous talk: https://www.youtube.com/watch?v=UFdzu2BiP1s

== Presentation formats

Preferred: Presentation - 60 mins

=== Available as:
* [x] Presentation - 30 mins
* [x] Presentation - 60 mins
* [ ] Code Kata walkthrough
* [ ] Lab exercise - 1h

= Speaker Bio

include::../AboutChandraGuntur.adoc[]
